# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kimcatchy"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/kimcatchy"

[social.params]
icon = "brand-gitlab"

[[main]]
identifier = "about"
name = "About"
url = "/about/"
[main.params]
icon = "user"